-- MySQL Script generated by MySQL Workbench
-- Wed Jun 24 10:45:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema carshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema carshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carshop` DEFAULT CHARACTER SET utf8 ;
USE `carshop` ;

-- -----------------------------------------------------
-- Table `carshop`.`cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carshop`.`cars` (
  `idcars` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NOT NULL,
  `fuel` VARCHAR(45) NOT NULL,
  `manmodel` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  `noise` INT NOT NULL,
  `pollution` INT NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`idcars`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
