/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.String;
import connectSQL.connectSQL;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Scanner;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Amy
 */
public class primary extends javax.swing.JFrame {

 
    connectSQL cc= new connectSQL();
    Connection con=cc.toConnect();
    
    
    
    
    
    
    public primary() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(getBackground());
        viewData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCars = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        iremscrudapp = new javax.swing.JLabel();
        modelcar = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        price = new javax.swing.JLabel();
        numPrice = new javax.swing.JTextField();
        manname = new javax.swing.JLabel();
        txtMan = new javax.swing.JTextField();
        prodyear = new javax.swing.JLabel();
        numYear = new javax.swing.JTextField();
        noiselevel = new javax.swing.JLabel();
        numNoise = new javax.swing.JTextField();
        carshop = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        cbFuel = new javax.swing.JComboBox<>();
        fueltype = new javax.swing.JLabel();
        poltax = new javax.swing.JLabel();
        numPollution = new javax.swing.JTextField();
        checkbox = new javax.swing.JCheckBox();
        Diesel = new javax.swing.JButton();
        Gas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        All = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        priceTotal = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        tableCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableCars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCarsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCars);

        jPanel1.setBackground(new java.awt.Color(175, 204, 204));

        iremscrudapp.setText("iRemsCRUD - App");

        modelcar.setText("Model car:");

        price.setText("Price: ($)");

        numPrice.setToolTipText("");
        numPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPriceActionPerformed(evt);
            }
        });

        manname.setText("Manufacter Name:");

        prodyear.setText("Production Year:");

        noiselevel.setText("Noise Level: (db)");

        carshop.setFont(new java.awt.Font("Freestyle Script", 0, 60)); // NOI18N
        carshop.setText("CarShop");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnNew.setText("Clear Fields");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        cbFuel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diesel", "Gas" }));
        cbFuel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFuelItemStateChanged(evt);
            }
        });
        cbFuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFuelActionPerformed(evt);
            }
        });

        fueltype.setText("Fuel Type:");

        poltax.setText("Pollution Tax:");
        poltax.setToolTipText("");

        numPollution.setToolTipText("");
        numPollution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPollutionActionPerformed(evt);
            }
        });

        checkbox.setBackground(new java.awt.Color(175, 204, 204));
        checkbox.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        checkbox.setText("Additional Electrical Engine for Gas only");
        checkbox.setEnabled(false);
        checkbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxItemStateChanged(evt);
            }
        });
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iremscrudapp))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(manname, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(noiselevel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(price, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(prodyear, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(poltax, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modelcar)
                            .addComponent(fueltype)))
                    .addComponent(btnNew))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(btnCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(numNoise, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                    .addComponent(txtModel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numPrice, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numPollution, javax.swing.GroupLayout.Alignment.LEADING))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(numYear, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbFuel, javax.swing.GroupLayout.Alignment.LEADING, 0, 233, Short.MAX_VALUE)
                                    .addComponent(txtMan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkbox, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(carshop))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(carshop, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelcar)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fueltype))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkbox)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manname)
                    .addComponent(txtMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodyear)
                    .addComponent(numYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noiselevel)
                    .addComponent(numNoise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numPollution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poltax))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price)
                    .addComponent(numPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnCreate)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate))
                .addGap(38, 38, 38)
                .addComponent(iremscrudapp)
                .addContainerGap())
        );

        Diesel.setText("Diesel");
        Diesel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DieselMouseClicked(evt);
            }
        });
        Diesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DieselActionPerformed(evt);
            }
        });

        Gas.setText("Gas");
        Gas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GasActionPerformed(evt);
            }
        });

        jLabel1.setText("Filter Cars");

        jLabel2.setText("or");

        All.setText("All");
        All.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllActionPerformed(evt);
            }
        });

        jButton1.setText("Export Diesel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Export Gas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        priceTotal.setText("Total Price of all Engines");
        priceTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTotalActionPerformed(evt);
            }
        });

        jButton3.setText("Calculate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(All)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Gas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Diesel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priceTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(21, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel1)
                    .addComponent(All)
                    .addComponent(Gas)
                    .addComponent(jLabel2)
                    .addComponent(Diesel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        
        insertData();
        clearBox();
        viewData();
        
        
    }//GEN-LAST:event_btnCreateActionPerformed
    
        public void sumPrice(){
            
            
       
        }
            
  

       
       
       
        
        public void exportData(String value){
        String[] registered=new String[8];
        String[] number={"ID","Model Car","Fuel Type","Manufacter Name","Year","Noise (db)","Pollution Tax ($)","Price ($)"};
        
       
               
           
            String filename = "d:\\"+value+" engines.txt";
        
        
    
        DefaultTableModel model=new DefaultTableModel(null, number);
        
       String SQL="select * from cars where fuel like '%"+value+"%'";
               
        
        try {
            FileWriter r = new FileWriter(filename);
            Statement st=con.createStatement();
            ResultSet rs2=st.executeQuery(SQL);
            
            while(rs2.next()){
                registered[0]=rs2.getString("idcars");
                r.append(registered[0]+".");
                
                registered[1]=rs2.getString("model");
                r.append(registered[1]+" ");
                
                registered[2]=rs2.getString("fuel");
                r.append(registered[2]+" ");
                
                registered[3]=rs2.getString("manmodel");
                r.append(registered[3]+" ");
                
                registered[4]=rs2.getString("year");
                r.append(registered[4]+" ");
                
                registered[5]=rs2.getString("noise");
                r.append(registered[5]+" ");
                
                registered[6]=rs2.getString("pollution");
                r.append(registered[6]+" ");
                
                registered[7]=rs2.getString("price");
                r.append(registered[7]+" ");
                
                r.append("\n");
                
               
                 
            model.addRow(registered);
                
            }
             JOptionPane.showMessageDialog(null,"Export Successfuly");
            r.close();
            tableCars.setModel(model);
        }   catch (Exception e) {
            JOptionPane.showMessageDialog(null,""+e.getMessage());
        }
        
    }
   
      



    public void viewData(){
        
        String[] number={"ID","Model Car","Fuel Type","Manufacter Name","Year","Noise (db)","Pollution Tax ($)","Price ($)"};
        String[] registered=new String[8];
        
        DefaultTableModel model=new DefaultTableModel(null, number);
        
        String SQL="select * from cars";
               
        
        try {
            
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(SQL);
            
            while(rs.next()){
                registered[0]=rs.getString("idcars");
                registered[1]=rs.getString("model");
                registered[2]=rs.getString("fuel");
                registered[3]=rs.getString("manmodel");
                registered[4]=rs.getString("year");
                registered[5]=rs.getString("noise");
                registered[6]=rs.getString("pollution");
                registered[7]=rs.getString("price");
                
               
            model.addRow(registered);
                
            }
            tableCars.setModel(model);
        }   catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error showing data"+e.getMessage());
        }
        
    }
    
    public void filterData(String value){
        
        String[] number={"ID","Model Car","Fuel Type","Manufacter Name","Year","Noise (db)","Pollution Tax ($)","Price ($)"};
        String[] registered=new String[8];
        
        DefaultTableModel model=new DefaultTableModel(null, number);
        
        String SQL="select * from cars where fuel like '%"+value+"%'";        
        
        try {
            
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(SQL);
            
            while(rs.next()){
                registered[0]=rs.getString("idcars");
                registered[1]=rs.getString("model");
                registered[2]=rs.getString("fuel");
                registered[3]=rs.getString("manmodel");
                registered[4]=rs.getString("year");
                registered[5]=rs.getString("noise");
                registered[6]=rs.getString("pollution");
                registered[7]=rs.getString("price");
                
                
            model.addRow(registered);
                
            }
            tableCars.setModel(model);
        }   catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error showing data"+e.getMessage());
        }
        
    }
    
    public void clearBox(){
        txtModel.setText("");
        cbFuel.setSelectedItem(null);
        txtMan.setText("");
        numYear.setText("");
        numNoise.setText("");
        numPollution.setText("");
        numPrice.setText("");
               
       
    }
    
    public void removeData(){
        
        int fileSelection=tableCars.getSelectedRow();
        
        try {
            String SQL="delete from cars where idcars="+tableCars.getValueAt(fileSelection,0);
            
            Statement st=con.createStatement();
            
            int n=st.executeUpdate(SQL);
            
            if(n>=0){
                JOptionPane.showMessageDialog(null,"Data Removed");
            }
            
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error removing data"+ e.getMessage());
        }
    }
  
    
    public void updateData(){
        
        try{
            
            String SQL="update cars set model=?, fuel=?, manmodel=?, year=?, noise=?, pollution=?, price=? where idcars=? ";
                
            int fileSelection=tableCars.getSelectedRow();
            String dao=(String)tableCars.getValueAt(fileSelection, 0);
            PreparedStatement pst=con.prepareStatement(SQL);
            
            pst.setString(1, txtModel.getText());
            
            int selectie=cbFuel.getSelectedIndex();
            pst.setString(2, cbFuel.getItemAt(selectie));
                       
            pst.setString(3, txtMan.getText());
            
            pst.setString(4, numYear.getText());
            
            pst.setString(5, numNoise.getText());
            
            pst.setString(6, numPollution.getText());
            
            pst.setString(7, numPrice.getText());
            
            pst.setString(8, dao);
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Element updated!");
                   
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
    }
    
   

    public void insertData(){
        
        try{
            
            String SQL="insert into cars (model, fuel, manmodel, year, noise, pollution, price) values(?,?,?,?,?,?,?)";
                  
            PreparedStatement pst=con.prepareStatement(SQL);
            
            pst.setString(1, txtModel.getText());
            
            int selectie=cbFuel.getSelectedIndex();
            pst.setString(2, cbFuel.getItemAt(selectie));
                       
            pst.setString(3, txtMan.getText());
            
            pst.setString(4, numYear.getText());
            
            pst.setString(5, numNoise.getText());
            
            pst.setString(6, numPollution.getText());
            
            pst.setString(7, numPrice.getText());
                       
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Registered");
                   
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
    }
    
    
            
            
    private void cbFuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFuelActionPerformed
       
        
        
       
        
    }//GEN-LAST:event_cbFuelActionPerformed
                
    private void numPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numPriceActionPerformed

    private void numPollutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPollutionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numPollutionActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
       clearBox();
    }//GEN-LAST:event_btnNewActionPerformed

    private void tableCarsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCarsMouseClicked

        int fileSelection=tableCars.rowAtPoint(evt.getPoint());
        
       
        txtModel.setText(tableCars.getValueAt(fileSelection, 1).toString());
        cbFuel.setSelectedItem(tableCars.getValueAt(fileSelection, 2).toString());
        txtMan.setText(tableCars.getValueAt(fileSelection, 3).toString());
        numYear.setText(tableCars.getValueAt(fileSelection, 4).toString());
        numNoise.setText(tableCars.getValueAt(fileSelection, 5).toString());
        numPollution.setText(tableCars.getValueAt(fileSelection, 6).toString());
        numPrice.setText(tableCars.getValueAt(fileSelection, 7).toString());
    }//GEN-LAST:event_tableCarsMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       updateData();
       clearBox();
       viewData();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        removeData();
        clearBox();
        viewData();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void GasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GasActionPerformed
         filterData("Gas");
    }//GEN-LAST:event_GasActionPerformed

    private void DieselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DieselActionPerformed
        
    }//GEN-LAST:event_DieselActionPerformed

    private void DieselMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DieselMouseClicked
          filterData("Diesel"); 
    }//GEN-LAST:event_DieselMouseClicked

    private void AllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllActionPerformed
         filterData("");
    }//GEN-LAST:event_AllActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        exportData("Diesel");
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        exportData("Gas");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void priceTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTotalActionPerformed
     
    }//GEN-LAST:event_priceTotalActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            try{
           String sql="Select sum(price) from cars";
           PreparedStatement pst=con.prepareStatement(sql);
           ResultSet rs=pst.executeQuery();
           if(rs.next()){
               String sum=rs.getString("sum(price)");
               priceTotal.setText(sum+"$");
           }           
            
           
       }
       catch(Exception e){
           
       }
        
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbFuelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFuelItemStateChanged
    
      
    }//GEN-LAST:event_cbFuelItemStateChanged

    private void checkboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxItemStateChanged
      
    }//GEN-LAST:event_checkboxItemStateChanged

    private void checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActionPerformed
          
        if (checkbox.isSelected())
           numPrice.setText("500"); 
           else numPrice.setText("350");
    }//GEN-LAST:event_checkboxActionPerformed
   
    /**
     * @param args the command line arguments
     */
        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(primary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(primary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(primary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(primary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new primary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton All;
    private javax.swing.JButton Diesel;
    private javax.swing.JButton Gas;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel carshop;
    private javax.swing.JComboBox<String> cbFuel;
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JLabel fueltype;
    private javax.swing.JLabel iremscrudapp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manname;
    private javax.swing.JLabel modelcar;
    private javax.swing.JLabel noiselevel;
    private javax.swing.JTextField numNoise;
    private javax.swing.JTextField numPollution;
    private javax.swing.JTextField numPrice;
    private javax.swing.JTextField numYear;
    private javax.swing.JLabel poltax;
    private javax.swing.JLabel price;
    private javax.swing.JTextField priceTotal;
    private javax.swing.JLabel prodyear;
    private javax.swing.JTable tableCars;
    private javax.swing.JTextField txtMan;
    private javax.swing.JTextField txtModel;
    // End of variables declaration//GEN-END:variables

    private void filterData(JButton Diesel) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
